version: 0.0
os: linux

hooks:
  ApplicationStop:
    - timeout: 300
      runas: root
      command: |
        echo "Stopping existing container..."
        docker stop admin-container || true
        docker rm admin-container || true

  AfterInstall:
    - timeout: 300
      runas: root
      command: |
        echo "Pulling latest image from ECR..."
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 495599757751.dkr.ecr.us-east-1.amazonaws.com
        docker pull 495599757751.dkr.ecr.us-east-1.amazonaws.com/admin:latest
        echo "Starting new container..."
        docker run -d -p 5000:5000 --name admin-container 495599757751.dkr.ecr.us-east-1.amazonaws.com/admin:latest
