version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "admin"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
  commands:
    - echo "Installing Python dependencies..."
    - echo "Listing files to confirm path..."
    - ls -R
    - pip install -r day-13/simple-python-app/requirements.txt

  build:
    commands:
      - echo "Building Docker image..."
      - cd day-13/simple-python-app/
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 495599757751.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 495599757751.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: day-13/simple-python-app
