version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "admin"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 495599757751.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - cd day-14/simple-python-app  # Navigate to the directory containing the Dockerfile
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .  # Build image in the correct folder
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 495599757751.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 495599757751.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Image pushed successfully!"
